# Generated by Django 5.2.2 on 2025-06-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/default-user-picture.webp', null=True, upload_to='avatars/'),
        ),
    ]
