# Generated by Django 5.2.2 on 2025-06-13 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='Verifity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verify_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default-user-picture.webp', null=True, upload_to='avatars/'),
        ),
    ]
