# Generated by Django 5.2.2 on 2025-06-13 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0004_profile_is_verify_profile_verify_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
