# Generated by Django 5.2.2 on 2025-06-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0006_profile_informate_about_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='informate_about_views',
            field=models.CharField(choices=[('True', 'Да'), ('False', 'Нет')], default='False', max_length=5, verbose_name='Уведомлять о просмотрах по почте'),
        ),
    ]
