# Generated by Django 5.2.2 on 2025-06-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_website', '0002_post_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='view_count',
        ),
    ]
